[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "tfm-iebs"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "pandas",
    "numpy",
    "scikit-learn",
    "sqlalchemy",
    "psycopg",
    "python-dotenv",
    "pymongo",
    "matplotlib",
    "pyarrow",
    "fastparquet",
    "tensorflow",
    "joblib",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]
